### ISSUE TITLE
Homepage not loading due to PBJ being deprecated

### ISSUE THREAD

**Issue by Objectful** [GoodTube/GoodTube#1]
wen fix ??!?>?!?><!!?<><?!<>? 
![image](https://user-images.githubusercontent.com/73402079/133313767-7ee836cf-1e7a-45d6-9671-968c781b7807.png)

**Comment by syndiate** [comment]
Yes, I'm aware of this.

**Comment by syndiate** [comment]
Fixed.

**Comment by ClassicTube** [comment]
wait

**Comment by ClassicTube** [comment]
then where is the update?
